### ISSUE TITLE
question: Appium on Windows

### ISSUE THREAD

**Issue by trabulmonkee** [Dragoon013/appium101#1]
For the training session, what did you use/do to get Appium installed and working on Windows?

I am following http://appium.io/slate/en/v1.1.0/?ruby#running-appium-on-windows, is there some process that should be followed?

**Comment by Dragoon013** [comment]
I followed parts of that process. A lot of the steps in there can be handled by just installing the Appium GUI. (Just click on the **Download Appium** link at http://appium.io/)

I can append a file into the repo that will contain the full steps and setup that we followed.

**Comment by Dragoon013** [comment]
If you look at the latest commit, I've uploaded a rough pdf of the steps. Please reopen if there are further issues regarding the setup (on windows).

**Comment by trabulmonkee** [comment]
Excellent, going through it now, thanks!
